FROM public.ecr.aws/docker/library/node:24.13.1-slim
LABEL maintainer="Mahesh <mahesh@ilimi.in>"
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    libsnappy-dev \
    libsnappy1v5 \
    zip \
 && apt-get upgrade -y \
 && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /opt/telemetry
ADD src /opt/telemetry/
WORKDIR /opt/telemetry/
RUN npm ci --omit=dev
WORKDIR /opt
CMD ["zip", "-r", "telemetry-service.zip", "telemetry"]